version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports: 
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  my-db:
